#!/usr/bin/env node
// ==========================================
// Scripting configurations
// ==========================================
const caporal = require('@caporal/core').program;

// Here, you could add custom global options, or tweak
// the Caporal instance, if required.

// Then it is run:
require(`${__dirname}/node_modules/@villemontreal/core-utils-scripting-core-nodejs-lib/dist/src/run`).run({
  caporal,
  projectRoot: __dirname,
  scriptsIndexModule: `./scripts/index`,
  testsLocations: [`./src/**/*.test.js`, `./tests/**/*.test.js`]
});
