# method and path
POST /fake-hail:
  code: 200
  headers:
    Content-Type: "application/json"
  body: |-
    {
      "data": [
        {
          "creation_datetime": "Thu, 22 Dec 2016 11:24:53 -0000",
          "customer_address": "801 rue Brennan, Montreal QC H3C 0G4",
          "customer_id": "vdm_tester1",
          "customer_lat": 45.58017,
          "customer_lon": -73.61479,
          "customer_phone_number": "514 999-9999",
          "id": "hvuJ45S",
          "incident_customer_reason": null,
          "incident_taxi_reason": null,
          "last_status_change": "Thu, 22 Dec 2016 11:24:53 -0000",
          "operateur": "coop",
          "rating_ride": null,
          "rating_ride_reason": null,
          "reporting_customer": null,
          "reporting_customer_reason": null,
          "status": "received",
          "taxi": {
            "id": "tPc79rW",
            "last_update": 1482423893,
            "position": {
              "lat": 45.6164341134,
              "lon": -73.6138161294
            }
          },
          "taxi_phone_number": null
        }
      ]
    }
POST /fake-hail-with-phone:
  code: 200
  headers:
    Content-Type: "application/json"
  body: |-
    {
      "data":[
          {
            "taxi_phone_number":"514 302-3022",
            "incident_taxi_reason":null,
            "reporting_customer_reason":null,
            "status":null
          }
      ]
    }
POST /fake-hail-invalid-json:
  code: 200
  headers:
    Content-Type: "application/json"
  body: |-
    {
      "data": [
        {
          "reporting_customer": true,
          "reporting_customer_reason": "payment",
      ]
    }
POST /fake-hail-null:
  code: 200
  headers:
    Content-Type: "application/json"
  body: |-
POST /fake-hail-error:
  code: 500
  headers:
    Content-Type: "application/json"
  body: |-
    { "error": "Bang!"}
GET /fake-open-data-taxi-areas:
  code: 200
  headers:
    Content-Type: "application/json"
  body: |-
    {
      "features": [
        {
          "properties": {
            "Nom": "test0",
            "Lat": 45.54753,
            "Long": -73.46092
          }
        },
        {
          "properties": {
            "Nom": "test1",
            "Lat": 45.51598,
            "Long": -73.41185
          }
        },
        {
          "properties": {
            "Nom": "test2",
            "Lat": 45.46498,
            "Long": -73.46612
          }
        }
      ]
    }
