# method and path
GET /fake-open-data-taxi-areas:
  code: 200
  headers:
    Content-Type: "application/json"
  body: |-
    {
      "features": [
        {
          "properties": {
            "Nom": "test0",
            "Lat": 45.54753,
            "Long": -73.46092
          }
        },
        {
          "properties": {
            "Nom": "test1",
            "Lat": 45.51598,
            "Long": -73.41185
          }
        },
        {
          "properties": {
            "Nom": "test2",
            "Lat": 45.46498,
            "Long": -73.46612
          }
        }
      ]
    }
