api:
  scheme: http
  host: localhost
  domainPath: ""
caching:
  taxisMaxAgeInSec: 10
  usersMaxAgeInSec: 10
dataSources:
  postgres:
    host: montreal-taxi-registry-postgre
    user: vdm_txp
    password: vdm_txp
  mongo:
    host1: montreal-taxi-registry-mongo
    port: 27017
    username: vdm_txp
    password: vdm_txp
    options: authSource=admin
