api:
  scheme: http
  host: localhost
  domainPath: ""
caching:
  taxisMaxAgeInSec: 10
  usersMaxAgeInSec: 10
dataSources:
  postgres:
    host: localhost
    port: 5432
    database: vdm_txp
    user: vdm_txp
    password: vdm_txp
