version: "3.8"

services:
  montreal-taxi-registry-dev-container:
    image: mcr.microsoft.com/devcontainers/javascript-node
    ports:
      - 12345:12345
      - 12366:12366
    volumes:
      # Mount the root folder that contains .git
      - ../:/workspace:cached
    container_name: montreal-taxi-registry-dev-container
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on: [montreal-taxi-registry-postgre]
    command: sleep infinity

  montreal-taxi-registry-postgre:
    image: postgis/postgis:15-3.5
    container_name: montreal-taxi-registry-postgre
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: vdm_txp
      POSTGRES_USER: vdm_txp
      POSTGRES_PASSWORD: vdm_txp

  montreal-taxi-registry-mongo:
    image: mongo:8.0.21
    container_name: montreal-taxi-registry-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: vdm_txp
      MONGO_INITDB_ROOT_PASSWORD: vdm_txp
    ports:
      - "27020:27017"

  montreal-taxi-registry-osrm:
    build:
      context: ../le-taxi-osrm
      dockerfile: ../le-taxi-osrm/Dockerfile
    container_name: montreal-taxi-registry-osrm
    ports:
      - 5000:5000

volumes:
  vendor: null
