#!groovy

@Library('cicd-lib')
import vdmtl.cicd.*
import jenkins.model.*

pipeline = new Pipeline()

// For more information on the configuration options,
// see https://bitbucket.org/villemontreal/cicd-lib/src/master/docs/Config.md
ctx = pipeline.createContext([
    namespace: ["sn","le-taxi"],
    application: [
        name: "le-taxi-osrm",
        tier: "backend",
        type: "service",
        description: "Server running OSRM API",
        keywords: ["taxi", "OSRM", "API"],
    ],
    build: [
        branchOverrides: [
            "feature/TM-1835-update-maps": "develop",
        ],
    ],
    packaging: [
        dockerfilePath: "./le-taxi-osrm/Dockerfile",
        dockerContextPath: "./le-taxi-osrm/",
    ],
    execution: [
        service: [
            port: 5000
        ],
        resources: [
            minCpu: "500m",
            maxCpu: "1000m",
            minMemory: "1024Mi",
            maxMemory: "2048Mi"
        ],
        autoScaling: [
            minReplicas: 2,
            maxReplicas: 2,
            cpuUsagePercentage: 70
        ],
        probes: [
            liveness: [
                enabled: true,
                path: '/route/v1/car/-73.619731,45.620407;-73.619000,45.620000?overview=false'
            ],
            readiness: [
                enabled: true,
                path: '/route/v1/car/-73.619731,45.620407;-73.619000,45.620000?overview=false'
            ],
        ],
        monitoring: [
            enabled: false,
            path: "/metrics"
        ],
        overrides: [
            "dev": [
                autoScaling: [
                    minReplicas: 1,
                    maxReplicas: 1,
                ],
            ],
            "accept": [
                autoScaling: [
                    minReplicas: 1,
                    maxReplicas: 1,
                ],
            ],
        ],
    ],
    approval: [
        enable: true,
        overrides: [
            "accept": [
                approvers: [
                    "uperr3a",
                    "ubrodda",
                    "ulebl5h",
                ],
            ],
            "prod": [
                approvers: [
                    "uperr3a",
                    "ubrodda",
                    "ulebl5h",
                ],
            ],
        ]
    ],
    notifications: [
        mail: [
            to: [
                "matthieu.perrin",
                "daniel.brodeur",
                "stephane.leblanc",
            ],
        ],
        chat: [
            room: "taximtl-cicd",
            notify: true,
        ],
    ],
    api: [
        domainPath: "/taxi/taxi-registry-osrm",
        stripUri: true,
        networkAccess: [
            profile: "internal",
        ],
        security: [
            enabled: false,
        ],
    ]
])

pipeline.start(ctx) {

    pipeline.withSourceCode(ctx) {

        pipeline.buildStage(ctx) {
            pipeline.buildDockerImage(ctx)
        }

        pipeline.prePublishStage(ctx) {
            pipeline.publishDraftDockerImage(ctx)
        }
    }

    pipeline.withDraftDockerImage(ctx) {

        pipeline.publishStage(ctx) {
            pipeline.publishDockerImage(ctx)
        }

        pipeline.deployStage(ctx) {
            pipeline.deployApp(ctx)

        }
    }
}
