#==========================================
# Api Tests
#==========================================
apiTests:
  env: localhost
  rootApiKey:
  user:
  password:
environment:
  isLocal: false
#==========================================
# End to End testing
#==========================================
e2eTesting:
  maxTestConcurrency: 30
inquiries:
  delayToExceedPromotion: 11
caching:
  delayToExceedUsersCache: 11

#==========================================
# Routing Service OSRM
#==========================================
taxiRegistryOsrmApi:
  base: https://api.dev.interne.montreal.ca
  domainPath: /api/taxi/taxi-registry-osrm
  route: route
  version: v1
  estimation:
    biasInSec: 336 # Bias calculated against Polytechnic's data to even the distribution over/under
    requestAndDispatchInSec: 120 # Arbitrary time to account for the taxi request and dispatch