name: Check License Lines
on:
  push:
    branches: [feature/*, develop, release/*, master]
jobs:
  check-license-lines:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check License Lines
      uses: kt3k/license_checker@v1.0.6